version: '3'

services:
  docs:
    image: building_dialouge_webapp_local_docs
    container_name: building_dialouge_webapp_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./building_dialouge_webapp:/app/building_dialouge_webapp:z
    ports:
      - '9000:9000'
    command: /start-docs
