# Generated by Django 4.2.12 on 2024-09-09 15:06

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(default='start', max_length=50)),
                ('roof_type', models.CharField(blank=True, choices=[('flachdach', 'Flachdach'), ('satteldach', 'Satteldach'), ('walmdach', 'Walmdach')], max_length=50, null=True)),
                ('roof_area', models.FloatField(blank=True, null=True)),
                ('roof_orientation', models.CharField(blank=True, max_length=100, null=True)),
                ('number_roof_windows', models.IntegerField(blank=True, null=True)),
                ('roof_usage', models.CharField(blank=True, max_length=100, null=True)),
                ('roof_insulation_exists', models.BooleanField(blank=True, null=True)),
                ('ventilation_system', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
