# Generated by Django 5.1.5 on 2025-03-11 13:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Solarthermal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(choices=[("heat", "heat"), ("load", "load")]),
                ),
                ("temperature", models.IntegerField()),
                ("elevation_angle", models.IntegerField()),
                ("direction_angle", models.IntegerField()),
                (
                    "profile",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=None
                    ),
                ),
            ],
        ),
    ]
