# Generated by Django 5.1.5 on 2025-03-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("heat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solarthermal",
            name="type",
            field=models.CharField(),
        ),
        migrations.AlterUniqueTogether(
            name="solarthermal",
            unique_together={
                ("type", "temperature", "elevation_angle", "direction_angle")
            },
        ),
    ]
