# Generated by Django 4.2.12 on 2024-09-23 09:51

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('heat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='number_roof_windows',
        ),
        migrations.RemoveField(
            model_name='building',
            name='roof_area',
        ),
        migrations.RemoveField(
            model_name='building',
            name='roof_insulation_exists',
        ),
        migrations.RemoveField(
            model_name='building',
            name='roof_orientation',
        ),
        migrations.RemoveField(
            model_name='building',
            name='roof_type',
        ),
        migrations.RemoveField(
            model_name='building',
            name='roof_usage',
        ),
        migrations.RemoveField(
            model_name='building',
            name='ventilation_system',
        ),
        migrations.AlterField(
            model_name='building',
            name='state',
            field=django_fsm.FSMField(choices=[('Bestandsaufnahme', 'Bestandsaufnahme'), ('Dach', 'Dach'), ('Dach_in_progress', 'Dach_in_progress'), ('Fenster', 'Fenster')], default=('Bestandsaufnahme', 'Bestandsaufnahme'), max_length=50),
        ),
        migrations.CreateModel(
            name='Roof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roof_state', django_fsm.FSMField(choices=[('roof_type', 'roof_type'), ('roof_type_flach', 'roof_type_flach'), ('roof_type_walm', 'roof_type_walm'), ('roof_details', 'roof_details'), ('roof_insulation', 'roof_insulation'), ('ventilation_system', 'ventilation_system')], default=('roof_type', 'roof_type'), max_length=50)),
                ('roof_type', models.CharField(blank=True, choices=[('flachdach', 'Flachdach'), ('satteldach', 'Satteldach'), ('walmdach', 'Walmdach')], max_length=50, null=True)),
                ('roof_area', models.FloatField(blank=True, null=True)),
                ('roof_orientation', models.CharField(blank=True, max_length=100, null=True)),
                ('number_roof_windows', models.IntegerField(blank=True, null=True)),
                ('roof_usage', models.CharField(blank=True, max_length=100, null=True)),
                ('roof_insulation_exists', models.BooleanField(blank=True, null=True)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='heat.building')),
            ],
        ),
    ]
