# Generated by Django 4.2.12 on 2024-10-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow_base', '__first__'),
        ('heat', '0002_remove_building_number_roof_windows_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoofProcess',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Roof process',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('viewflow_base.process',),
        ),
        migrations.RemoveField(
            model_name='roof',
            name='building',
        ),
        migrations.RemoveField(
            model_name='roof',
            name='roof_state',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
    ]
