# Generated by Django 5.0.8 on 2025-03-21 12:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat', '0002_alter_solarthermal_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photovoltaic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevation_angle', models.IntegerField()),
                ('direction_angle', models.IntegerField()),
                ('profile', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
            options={
                'unique_together': {('elevation_angle', 'direction_angle')},
            },
        ),
    ]
