# Generated by Django 5.2 on 2025-04-15 08:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("heat", "0004_hotwater_heatpump_load"),
    ]

    operations = [
        migrations.CreateModel(
            name="Heat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=None
                    ),
                ),
            ],
        ),
    ]
